//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int Id_producto { get; set; }
        public string Nombre_producto { get; set; }
        public string Marca_producto { get; set; }
        public int Precio_producto { get; set; }
        public int Stock_producto { get; set; }
        public System.DateTime Fecha_Termino_Subasta { get; set; }
        public int Id_Retail { get; set; }
    
        public virtual Retail Retail { get; set; }
    }
}
