//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public int Id_tarjeta { get; set; }
        public int saldo_tarjeta { get; set; }
        public int linea_credito_tarjeta { get; set; }
        public int Id_Cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
