//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.ServicioLoginCliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioLoginCliente.ServiceProducto")]
    public interface ServiceProducto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceProducto/AgregarProducto", ReplyAction="http://tempuri.org/ServiceProducto/AgregarProductoResponse")]
        bool AgregarProducto(int idpro, string nombrepro, string marcapro, int preciopro, int stockpro, System.DateTime fechapro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceProducto/AgregarProducto", ReplyAction="http://tempuri.org/ServiceProducto/AgregarProductoResponse")]
        System.Threading.Tasks.Task<bool> AgregarProductoAsync(int idpro, string nombrepro, string marcapro, int preciopro, int stockpro, System.DateTime fechapro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceProducto/LoginWSCliente", ReplyAction="http://tempuri.org/ServiceProducto/LoginWSClienteResponse")]
        bool LoginWSCliente(int id, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceProducto/LoginWSCliente", ReplyAction="http://tempuri.org/ServiceProducto/LoginWSClienteResponse")]
        System.Threading.Tasks.Task<bool> LoginWSClienteAsync(int id, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceProductoChannel : CapaPresentacion.ServicioLoginCliente.ServiceProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceProductoClient : System.ServiceModel.ClientBase<CapaPresentacion.ServicioLoginCliente.ServiceProducto>, CapaPresentacion.ServicioLoginCliente.ServiceProducto {
        
        public ServiceProductoClient() {
        }
        
        public ServiceProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AgregarProducto(int idpro, string nombrepro, string marcapro, int preciopro, int stockpro, System.DateTime fechapro) {
            return base.Channel.AgregarProducto(idpro, nombrepro, marcapro, preciopro, stockpro, fechapro);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarProductoAsync(int idpro, string nombrepro, string marcapro, int preciopro, int stockpro, System.DateTime fechapro) {
            return base.Channel.AgregarProductoAsync(idpro, nombrepro, marcapro, preciopro, stockpro, fechapro);
        }
        
        public bool LoginWSCliente(int id, string pass) {
            return base.Channel.LoginWSCliente(id, pass);
        }
        
        public System.Threading.Tasks.Task<bool> LoginWSClienteAsync(int id, string pass) {
            return base.Channel.LoginWSClienteAsync(id, pass);
        }
    }
}
