//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.ServiceAgregarProducto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAgregarProducto.ServiceProducto")]
    public interface ServiceProducto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceProducto/AgregarProducto", ReplyAction="http://tempuri.org/ServiceProducto/AgregarProductoResponse")]
        bool AgregarProducto(int idpro, string nombrepro, string marcapro, int preciopro, int stockpro, System.DateTime fechapro, int idretail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceProducto/AgregarProducto", ReplyAction="http://tempuri.org/ServiceProducto/AgregarProductoResponse")]
        System.Threading.Tasks.Task<bool> AgregarProductoAsync(int idpro, string nombrepro, string marcapro, int preciopro, int stockpro, System.DateTime fechapro, int idretail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceProducto/LoginWSCliente", ReplyAction="http://tempuri.org/ServiceProducto/LoginWSClienteResponse")]
        bool LoginWSCliente(int id, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceProducto/LoginWSCliente", ReplyAction="http://tempuri.org/ServiceProducto/LoginWSClienteResponse")]
        System.Threading.Tasks.Task<bool> LoginWSClienteAsync(int id, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceProducto/LoginWSUsuario", ReplyAction="http://tempuri.org/ServiceProducto/LoginWSUsuarioResponse")]
        bool LoginWSUsuario(int id, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceProducto/LoginWSUsuario", ReplyAction="http://tempuri.org/ServiceProducto/LoginWSUsuarioResponse")]
        System.Threading.Tasks.Task<bool> LoginWSUsuarioAsync(int id, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceProducto/ListadoProductos", ReplyAction="http://tempuri.org/ServiceProducto/ListadoProductosResponse")]
        CapaNegocio.Producto[] ListadoProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceProducto/ListadoProductos", ReplyAction="http://tempuri.org/ServiceProducto/ListadoProductosResponse")]
        System.Threading.Tasks.Task<CapaNegocio.Producto[]> ListadoProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceProducto/AgregarProducto2", ReplyAction="http://tempuri.org/ServiceProducto/AgregarProducto2Response")]
        bool AgregarProducto2(int idpro, string nombrepro, string marcapro, int preciopro, int stockpro, System.DateTime fechapro, int idretail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceProducto/AgregarProducto2", ReplyAction="http://tempuri.org/ServiceProducto/AgregarProducto2Response")]
        System.Threading.Tasks.Task<bool> AgregarProducto2Async(int idpro, string nombrepro, string marcapro, int preciopro, int stockpro, System.DateTime fechapro, int idretail);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceProductoChannel : CapaPresentacion.ServiceAgregarProducto.ServiceProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceProductoClient : System.ServiceModel.ClientBase<CapaPresentacion.ServiceAgregarProducto.ServiceProducto>, CapaPresentacion.ServiceAgregarProducto.ServiceProducto {
        
        public ServiceProductoClient() {
        }
        
        public ServiceProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AgregarProducto(int idpro, string nombrepro, string marcapro, int preciopro, int stockpro, System.DateTime fechapro, int idretail) {
            return base.Channel.AgregarProducto(idpro, nombrepro, marcapro, preciopro, stockpro, fechapro, idretail);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarProductoAsync(int idpro, string nombrepro, string marcapro, int preciopro, int stockpro, System.DateTime fechapro, int idretail) {
            return base.Channel.AgregarProductoAsync(idpro, nombrepro, marcapro, preciopro, stockpro, fechapro, idretail);
        }
        
        public bool LoginWSCliente(int id, string pass) {
            return base.Channel.LoginWSCliente(id, pass);
        }
        
        public System.Threading.Tasks.Task<bool> LoginWSClienteAsync(int id, string pass) {
            return base.Channel.LoginWSClienteAsync(id, pass);
        }
        
        public bool LoginWSUsuario(int id, string pass) {
            return base.Channel.LoginWSUsuario(id, pass);
        }
        
        public System.Threading.Tasks.Task<bool> LoginWSUsuarioAsync(int id, string pass) {
            return base.Channel.LoginWSUsuarioAsync(id, pass);
        }
        
        public CapaNegocio.Producto[] ListadoProductos() {
            return base.Channel.ListadoProductos();
        }
        
        public System.Threading.Tasks.Task<CapaNegocio.Producto[]> ListadoProductosAsync() {
            return base.Channel.ListadoProductosAsync();
        }
        
        public bool AgregarProducto2(int idpro, string nombrepro, string marcapro, int preciopro, int stockpro, System.DateTime fechapro, int idretail) {
            return base.Channel.AgregarProducto2(idpro, nombrepro, marcapro, preciopro, stockpro, fechapro, idretail);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarProducto2Async(int idpro, string nombrepro, string marcapro, int preciopro, int stockpro, System.DateTime fechapro, int idretail) {
            return base.Channel.AgregarProducto2Async(idpro, nombrepro, marcapro, preciopro, stockpro, fechapro, idretail);
        }
    }
}
